routes/web.php
<?php

use App\Http\Controllers\Admin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
})->name('home');

Route::prefix('admin')->as('admin.')->middleware('guard:admin')->group(function () {


    Route::middleware('admin.guest')->group(function () {

        Route::get('login', [Admin\AuthenticatedSessionController::class, 'create'])->name('login');
        Route::post('login', [Admin\AuthenticatedSessionController::class, 'store']);

    });

    Route::middleware('admin.auth')->group(function () {

        Route::post('/logout', [Admin\AuthenticatedSessionController::class, 'destroy'])->name('logout');

        Route::get('/profile', [Admin\HomeController::class, 'showProfileForm'])->name('profile');
        Route::post('/profile', [Admin\HomeController::class, 'updateProfile'])->name('profile.update');

        Route::get('/', [Admin\HomeController::class, 'dashboard'])->name('dashboard');

        Route::resource('users', Admin\UsersController::class)->except(['create', 'store', 'show']);
        Route::post('users/{user}/renew', [Admin\UsersController::class, 'renew'])->name('users.renew');
        Route::resource('plans', Admin\PlansController::class)->except(['show']);
        Route::resource('card-groups', Admin\CardGroupsController::class)->names('groups')->except(['show'])->parameters([
            'card-groups' => 'group'
        ]);
        Route::resource('cards', Admin\CardsController::class)->except(['show']);
        Route::post('cards/{card}/generate-audio', [Admin\CardsController::class, 'generateAudio'])->name('cards.generateAudio');

        Route::prefix('settings')->group(function () {
            Route::get('general', [Admin\SettingsController::class, 'editGeneral'])->name('settings.edit.general');
            Route::put('general', [Admin\SettingsController::class, 'updateGeneral'])->name('settings.update.general');

            Route::get('app', [Admin\SettingsController::class, 'editApp'])->name('settings.edit.app');
            Route::put('app', [Admin\SettingsController::class, 'updateApp'])->name('settings.update.app');
        });

        Route::prefix('records')->group(function () {
            Route::get('unlock', [Admin\UserUnlockRecordsController::class, 'index'])->name('records.unlock');
            Route::get('collect', [Admin\UserCollectRecordsController::class, 'index'])->name('records.collect');
            Route::get('learn', [Admin\UserLearnRecordsController::class, 'index'])->name('records.learn');
            Route::get('subscription', [Admin\UserSubscriptionRecordsController::class, 'index'])->name('records.subscription');
            Route::get('online', [Admin\UserOnlineRecordsController::class, 'index'])->name('records.online');
            Route::get('online/{record}/items', [Admin\UserOnlineRecordsController::class, 'showItems'])->name('records.online.showItems');
        });

        Route::resource('feedback', Admin\FeedbackController::class)->only(['index', 'destroy']);
        Route::get('feedback/{feedback}/replies', [Admin\FeedbackController::class, 'showReplies'])->name('feedback.showReplies');
        Route::post('feedback/{feedback}/replies', [Admin\FeedbackController::class, 'storeReply'])->name('feedback.storeReply');

        Route::resource('abouts', Admin\AboutsController::class)->except(['show']);
        Route::get('abouts/{about}/content', [Admin\AboutsController::class, 'showContent'])->name('abouts.showContent');

        Route::prefix('filepond')->group(function () {
            Route::post('process', [Admin\FilepondUploadsController::class, 'process'])->name('filepond.process');
            Route::get('load', [Admin\FilepondUploadsController::class, 'load'])->name('filepond.load');
            Route::delete('revert', [Admin\FilepondUploadsController::class, 'revert'])->name('filepond.revert');
        });
    });

});

resources/views/partials/admin/footer.blade.php
<footer id="page-footer" class="flex flex-none items-center bg-white">
  <div class="text-center flex flex-col md:text-left md:flex-row md:justify-between text-sm max-w-10xl mx-auto px-4 lg:px-8 w-full">
    <div class="pt-4 pb-1 md:pb-4">
      <a href="#" target="_blank" class="font-medium text-indigo-600 hover:text-indigo-400">{{ config('app.name') }}</a> © 2021
    </div>
    <div class="pb-4 pt-1 md:pt-4 inline-flex items-center justify-center">
      <span>由</span>
      <a href="#" target="_blank" class="font-medium text-indigo-600 hover:text-indigo-400 mx-1">hipig</a>
      <span>设计和编码</span>
      <x-heroicon-s-heart class="w-4 h-4 mx-1 text-red-600"></x-heroicon-s-heart>
    </div>
  </div>
</footer>

resources/views/partials/admin/header.blade.php
<header
  id="page-header"
  class="flex flex-none items-center h-16 bg-white shadow-sm fixed top-0 right-0 left-0 z-30"
  x-bind:class="{
      'lg:pl-64': desktopSidebarOpen
    }"
>
  <div class="flex justify-between max-w-8xl mx-auto px-4 lg:px-8 w-full">
    <!-- Left Section -->
    <div class="flex items-center space-x-2">
      <!-- Toggle Sidebar on Desktop -->
      <div class="hidden lg:block">
        <button
          type="button"
          class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none px-3 py-2 leading-6 rounded border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none"
          x-on:click="desktopSidebarOpen = !desktopSidebarOpen"
        >
          <svg class="hi-solid hi-menu-alt-1 inline-block w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h6a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"/></svg>
        </button>
      </div>
      <!-- END Toggle Sidebar on Desktop -->

      <!-- Toggle Sidebar on Mobile -->
      <div class="lg:hidden">
        <button
          type="button"
          class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none px-3 py-2 leading-6 rounded border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none"
          x-on:click="mobileSidebarOpen = true"
        >
          <x-heroicon-s-menu-alt-1 class="w-5 h-5"></x-heroicon-s-menu-alt-1>
        </button>
      </div>
      <!-- END Toggle Sidebar on Mobile -->

      <!-- Search -->
      <div class="hidden sm:block">
        <form onsubmit="return false;">
          <input type="text" class="w-full block border border-gray-200 rounded px-3 py-2 leading-5 text-sm focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50" id="tk-form-layouts-search" placeholder="关键字.." />
        </form>
      </div>
      <div class="sm:hidden">
        <button type="button" class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none px-3 py-2 leading-5 text-sm rounded border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
          <x-heroicon-s-search class="w-5 h-5"></x-heroicon-s-search>
        </button>
      </div>
      <!-- END Search -->
    </div>
    <!-- END Left Section -->

    <!-- Right Section -->
    <div class="flex items-center space-x-2">
      <x-dropdown>
        <button
          type="button"
          class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none px-3 py-2 leading-5 text-sm rounded border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none"
        >
          <x-heroicon-o-bell class="w-5 h-5"></x-heroicon-o-bell>
          <span class="text-indigo-500">•</span>
        </button>
        <x-slot name="menu">
          <div class="w-72 bg-white ring-1 ring-black ring-opacity-5 rounded divide-y divide-gray-100">
            <ul class="py-2 divide-y divide-gray-100">
              <li>
                <a href="#" class="py-2 flex items-start hover:bg-gray-100 hover:text-gray-700">
                  <div class="mx-3">
                    <x-heroicon-s-check-circle class="w-5 h-5 text-green-500"></x-heroicon-s-check-circle>
                  </div>
                  <div class="flex-1 text-sm pr-2">
                    <div class="font-semibold">应用版本已升级至 v5.6！</div>
                    <div class="text-xs text-gray-400">3 分钟前</div>
                  </div>
                </a>
              </li>
              <li>
                <a href="#" class="py-2 flex items-start hover:bg-gray-100 hover:text-gray-700">
                  <div class="mx-3">
                    <x-heroicon-s-user-add class="w-5 h-5 text-indigo-500"></x-heroicon-s-user-add>
                  </div>
                  <div class="flex-1 text-sm pr-2">
                    <div class="font-semibold">有新的订阅用户，共计2580个！</div>
                    <div class="text-xs text-gray-400">10 分钟前</div>
                  </div>
                </a>
              </li>
              <li>
                <a href="#" class="py-2 flex items-start hover:bg-gray-100 hover:text-gray-700">
                  <div class="mx-3">
                    <x-heroicon-s-x-circle class="w-5 h-5 text-red-500"></x-heroicon-s-x-circle>
                  </div>
                  <div class="flex-1 text-sm pr-2">
                    <div class="font-semibold">服务器备份无法完成，请检查！</div>
                    <div class="text-xs text-gray-400">30 分钟前</div>
                  </div>
                </a>
              </li>
              <li>
                <a href="#" class="py-2 flex items-start hover:bg-gray-100 hover:text-gray-700">
                  <div class="mx-3">
                    <x-heroicon-s-exclamation-circle class="w-5 h-5 text-yellow-500"></x-heroicon-s-exclamation-circle>
                  </div>
                  <div class="flex-1 text-sm pr-2">
                    <div class="font-semibold">你的空间不够了，请考虑升级你的计划。</div>
                    <div class="text-xs text-gray-400">1 小时前</div>
                  </div>
                </a>
              </li>
            </ul>
            <div class="p-2">
              <button type="button" class="w-full inline-flex justify-center items-center space-x-2 rounded border font-semibold focus:outline-none px-3 py-2 leading-5 text-sm border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
                <x-heroicon-s-eye class="w-4 h-4"></x-heroicon-s-eye>
                <span>查看全部</span>
              </button>
            </div>
          </div>
        </x-slot>
      </x-dropdown>

      <x-dropdown>
        <button
          type="button"
          class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none px-3 py-2 leading-5 text-sm rounded border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none"
        >
          <span>{{ Auth::user()->name }}</span>
          <x-heroicon-s-chevron-down class="w-5 h-5 opacity-50"></x-heroicon-s-chevron-down>
        </button>
        <x-slot name="menu">
          <x-dropdown.menu>
            <div class="p-2 space-y-1">
              <x-dropdown.item label="个人资料" icon="heroicon-s-user-circle" href="{{ route('admin.profile') }}"></x-dropdown.item>
              <x-dropdown.item label="系统设置" icon="heroicon-s-cog" href="{{ route('admin.settings.edit.general') }}"></x-dropdown.item>
            </div>
            <div class="p-2 space-y-1">
              <x-dropdown.item label="退出登录" icon="heroicon-s-lock-closed" x-on:click="$refs['logout-form'].submit()"></x-dropdown.item>
              <form x-ref="logout-form" action="{{ route('admin.logout') }}" method="post">
                @csrf
              </form>
            </div>
          </x-dropdown.menu>
        </x-slot>
      </x-dropdown>
    </div>
    <!-- END Right Section -->
  </div>
</header>

resources/views/partials/admin/message.blade.php
@if($errors->count() > 0)
  <div x-data="{open: true}" x-show="open" class="p-4 md:p-5 rounded text-red-700 bg-red-100 relative">
    <div class="flex items-center mb-3 space-x-3">
      <x-heroicon-s-x-circle class="w-5 h-5 flex-none text-red-500" />
      <h3 class="font-semibold">
        请检查以下错误：
      </h3>
    </div>
    <ul class="list-inside ml-8 space-y-2">
      @foreach($errors->all() as $message)
        <li class="flex items-center space-x-2">
          <x-heroicon-s-arrow-narrow-right class="w-4 h-4 flex-none" />
          <span>{{ $message }}</span>
        </li>
      @endforeach
    </ul>
    <div class="absolute top-0 right-0 mt-4 mr-4 md:mt-5 md:mr-5">
      <button type="button" x-on:click="open = false" class="inline-flex justify-center items-center space-x-2 rounded border font-semibold focus:outline-none px-1 py-1 leading-5 text-sm border-transparent focus:ring focus:ring-opacity-50 text-red-600 hover:text-red-400 focus:ring-red-500 active:text-red-600">
        <x-heroicon-s-x class="w-5 h-5" />
      </button>
    </div>
  </div>
@endif

@if(session('info'))
  <x-alert type="info">{{ session('info') }}</x-alert>
@endif

@if(session('warning'))
  <x-alert type="warning">{{ session('warning') }}</x-alert>
@endif

@if(session('success'))
  <x-alert type="success">{{ session('success') }}</x-alert>
@endif

@if(session('error'))
  <x-alert type="error">{{ session('error') }}</x-alert>
@endif

resources/views/partials/admin/pagination.blade.php
@if ($paginator->hasPages())
  <nav role="navigation" aria-label="{{ __('Pagination Navigation') }}" class="flex items-center justify-between">
    <div class="flex justify-between flex-1 sm:hidden">
      @if ($paginator->onFirstPage())
        <span
          class="relative inline-flex items-center px-4 py-2 text-sm font-medium text-gray-400 bg-white border border-gray-300 cursor-default leading-5 rounded-md">
                    {!! __('pagination.previous') !!}
                </span>
      @else
        <a href="{{ $paginator->previousPageUrl() }}"
           class="relative inline-flex items-center px-4 py-2 text-sm font-medium text-indigo-600 bg-white border border-gray-300 leading-5 rounded-md hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring ring-indigo-600-300 active:bg-gray-100 transition ease-in-out duration-150">
          {!! __('pagination.previous') !!}
        </a>
      @endif

      @if ($paginator->hasMorePages())
        <a href="{{ $paginator->nextPageUrl() }}"
           class="relative inline-flex items-center px-4 py-2 ml-3 text-sm font-medium text-indigo-600 bg-white border border-gray-300 leading-5 rounded-md hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring ring-indigo-600-300 active:bg-gray-100 transition ease-in-out duration-150">
          {!! __('pagination.next') !!}
        </a>
      @else
        <span
          class="relative inline-flex items-center px-4 py-2 ml-3 text-sm font-medium text-gray-400 bg-white border border-gray-300 cursor-default leading-5 rounded-md">
                    {!! __('pagination.next') !!}
                </span>
      @endif
    </div>

    <div class="hidden sm:flex-1 sm:flex sm:items-center sm:justify-between">
      <div>
        <p class="text-gray-500 leading-5">
          显示第
          <span class="font-medium">{{ $paginator->firstItem() }}</span>
          至
          <span class="font-medium">{{ $paginator->lastItem() }}</span>
          ，共
          <span class="font-medium">{{ $paginator->total() }}</span>
          条数据
        </p>
      </div>

      <div>
        <div class="relative z-0 inline-flex shadow-sm rounded-md">
          {{-- Previous Page Link --}}
          @if ($paginator->onFirstPage())
            <span aria-disabled="true" aria-label="{{ __('pagination.previous') }}">
              <span
                class="relative inline-flex items-center px-2 py-2 text-sm font-medium text-gray-400 bg-white border border-gray-300 cursor-default rounded-l leading-5"
                aria-hidden="true">
                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                  <path fill-rule="evenodd"
                        d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                        clip-rule="evenodd"/>
                </svg>
              </span>
            </span>
          @else
            <a href="{{ $paginator->previousPageUrl() }}" rel="prev"
               class="relative inline-flex items-center px-2 py-2 text-sm font-medium text-indigo-600 bg-white border border-gray-300 rounded-l leading-5 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring ring-indigo-600-300 active:bg-gray-100 transition ease-in-out duration-150"
               aria-label="{{ __('pagination.previous') }}">
              <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd"
                      d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                      clip-rule="evenodd"/>
              </svg>
            </a>
          @endif

          {{-- Pagination Elements --}}
          @foreach ($elements as $element)
            {{-- "Three Dots" Separator --}}
            @if (is_string($element))
              <span aria-disabled="true">
                  <span
                    class="relative inline-flex items-center px-4 py-2 -ml-px text-sm font-medium text-gray-700 bg-white border border-gray-300 cursor-default leading-5">{{ $element }}</span>
              </span>
            @endif

            {{-- Array Of Links --}}
            @if (is_array($element))
              @foreach ($element as $page => $url)
                @if ($page == $paginator->currentPage())
                  <span aria-current="page">
                      <span
                        class="relative inline-flex items-center px-4 py-2 -ml-px text-sm font-medium text-white bg-indigo-600 border border-indigo-600 cursor-default leading-5">{{ $page }}</span>
                  </span>
                @else
                  <a href="{{ $url }}"
                     class="relative inline-flex items-center px-4 py-2 -ml-px text-sm font-medium text-indigo-600 bg-white border border-gray-300 leading-5 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring ring-indigo-600-300 active:bg-gray-100 transition ease-in-out duration-150"
                     aria-label="{{ __('Go to page :page', ['page' => $page]) }}">
                    {{ $page }}
                  </a>
                @endif
              @endforeach
            @endif
          @endforeach

          {{-- Next Page Link --}}
          @if ($paginator->hasMorePages())
            <a href="{{ $paginator->nextPageUrl() }}" rel="next"
               class="relative inline-flex items-center px-2 py-2 -ml-px text-sm font-medium text-indigo-600 bg-white border border-gray-300 rounded-r leading-5 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring ring-indigo-600-300 active:bg-gray-100 transition ease-in-out duration-150"
               aria-label="{{ __('pagination.next') }}">
              <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd"
                      d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                      clip-rule="evenodd"/>
              </svg>
            </a>
          @else
            <span aria-disabled="true" aria-label="{{ __('pagination.next') }}">
              <span
                class="relative inline-flex items-center px-2 py-2 -ml-px text-sm font-medium text-gray-400 bg-white border border-gray-300 cursor-default rounded-r leading-5"
                aria-hidden="true">
                  <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                      <path fill-rule="evenodd"
                            d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                            clip-rule="evenodd"/>
                  </svg>
              </span>
            </span>
          @endif
        </div>
      </div>
    </div>
  </nav>
@endif

resources/views/partials/admin/sidebar.blade.php
<nav
  id="page-sidebar"
  class="flex flex-col fixed top-0 left-0 bottom-0 w-full lg:w-64 h-full bg-sidebar-dark text-gray-200 z-50 transform transition-transform duration-500 ease-out"
  x-bind:class="{
      '-translate-x-full': !mobileSidebarOpen,
      'translate-x-0': mobileSidebarOpen,
      'lg:-translate-x-full': !desktopSidebarOpen,
      'lg:translate-x-0': desktopSidebarOpen,
    }"
  aria-label="Main Sidebar Navigation"
>
  <!-- Sidebar Header -->
  <div class="h-16 bg-gray-600 bg-opacity-25 flex-none flex items-center justify-between lg:justify-center px-4 w-full">
    <!-- Brand -->
    <a href="{{ route('admin.dashboard') }}" class="inline-flex items-center space-x-2 font-bold text-lg tracking-wide text-white-600 hover:text-white-400 text-white hover:opacity-75">
      <x-heroicon-o-cube-transparent class="w-5 h-5 text-indigo-400"></x-heroicon-o-cube-transparent>
      <span>{{ config('app.name') }}</span>
    </a>
    <!-- END Brand -->

    <!-- Close Sidebar on Mobile -->
    <div class="lg:hidden">
      <button
        type="button"
        class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none px-3 py-2 leading-5 text-sm rounded border-transparent text-white opacity-75 hover:opacity-100 focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:opacity-75"
        x-on:click="mobileSidebarOpen = false"
      >
        <x-heroicon-s-x class="w-4 h-4 -mx-1"></x-heroicon-s-x>
      </button>
    </div>
    <!-- END Close Sidebar on Mobile -->
  </div>
  <!-- END Sidebar Header -->

  <!-- Sidebar Navigation -->
  <div class="sidebar-scroll-section" data-simplebar>
    <x-sidebar.menu>
      <x-sidebar.item label="仪表盘" icon="heroicon-o-home" href="{{ route('admin.dashboard') }}" :active="if_route_pattern('admin.dashboard')"></x-sidebar.item>
      <x-sidebar.group label="系统">
        <x-sidebar.item label="系统设置" icon="heroicon-o-cog" :active="if_route_pattern('admin.settings.*')">
          <x-sidebar.subitem label="基础" href="{{ route('admin.settings.edit.general') }}" :active="if_route('admin.settings.edit.general')"></x-sidebar.subitem>
          <x-sidebar.subitem label="站点" href="{{ route('admin.settings.edit.app') }}" :active="if_route('admin.settings.edit.app')"></x-sidebar.subitem>
        </x-sidebar.item>
{{--        <x-sidebar.item label="管理员" icon="heroicon-o-shield-check"></x-sidebar.item>--}}
{{--        <x-sidebar.item label="角色" icon="heroicon-o-lock-closed"></x-sidebar.item>--}}
        <x-sidebar.item label="用户" icon="heroicon-o-user" href="{{ route('admin.users.index') }}" :active="if_route_pattern('admin.users.*')"></x-sidebar.item>
        <x-sidebar.item label="会员方案" icon="heroicon-o-server" href="{{ route('admin.plans.index') }}" :active="if_route_pattern('admin.plans.*')"></x-sidebar.item>
      </x-sidebar.group>
      <x-sidebar.group label="应用">
        <x-sidebar.item label="卡片分组" icon="heroicon-o-folder-open" href="{{ route('admin.groups.index') }}" :active="if_route_pattern('admin.groups.*')"></x-sidebar.item>
        <x-sidebar.item label="卡片" icon="heroicon-o-clipboard-list" href="{{ route('admin.cards.index') }}" :active="if_route_pattern('admin.cards.*')"></x-sidebar.item>
        <x-sidebar.item label="统计报告" icon="heroicon-o-chart-square-bar" :active="if_route_pattern('admin.records.*')">
          <x-sidebar.subitem label="会员订阅" href="{{ route('admin.records.subscription') }}" :active="if_route('admin.records.subscription')"></x-sidebar.subitem>
          <x-sidebar.subitem label="卡组解锁" href="{{ route('admin.records.unlock') }}" :active="if_route('admin.records.unlock')"></x-sidebar.subitem>
          <x-sidebar.subitem label="收藏记录" href="{{ route('admin.records.collect') }}" :active="if_route('admin.records.collect')"></x-sidebar.subitem>
          <x-sidebar.subitem label="在线时长" href="{{ route('admin.records.online') }}" :active="if_route('admin.records.online')"></x-sidebar.subitem>
          <x-sidebar.subitem label="卡片学习记录" href="{{ route('admin.records.learn') }}" :active="if_route('admin.records.learn')"></x-sidebar.subitem>
        </x-sidebar.item>
      </x-sidebar.group>
      <x-sidebar.group label="其他">
        <x-sidebar.item label="留言反馈" icon="heroicon-o-chat-alt" href="{{ route('admin.feedback.index') }}" :active="if_route_pattern('admin.feedback.*')"></x-sidebar.item>
        <x-sidebar.item label="关于我们" icon="heroicon-o-exclamation-circle" href="{{ route('admin.abouts.index') }}" :active="if_route_pattern('admin.abouts.*')"></x-sidebar.item>
      </x-sidebar.group>
    </x-sidebar.menu>
  </div>
  <!-- END Sidebar Navigation -->
</nav>