routes/web.php
<?php

use App\Http\Controllers\Admin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
})->name('home');

Route::prefix('admin')->as('admin.')->middleware('guard:admin')->group(function () {


    Route::middleware('admin.guest')->group(function () {

        Route::get('login', [Admin\AuthenticatedSessionController::class, 'create'])->name('login');
        Route::post('login', [Admin\AuthenticatedSessionController::class, 'store']);

    });

    Route::middleware('admin.auth')->group(function () {

        Route::post('/logout', [Admin\AuthenticatedSessionController::class, 'destroy'])->name('logout');

        Route::get('/profile', [Admin\HomeController::class, 'showProfileForm'])->name('profile');
        Route::post('/profile', [Admin\HomeController::class, 'updateProfile'])->name('profile.update');

        Route::get('/', [Admin\HomeController::class, 'dashboard'])->name('dashboard');

        Route::resource('users', Admin\UsersController::class)->except(['create', 'store', 'show']);
        Route::post('users/{user}/renew', [Admin\UsersController::class, 'renew'])->name('users.renew');
        Route::resource('plans', Admin\PlansController::class)->except(['show']);
        Route::resource('card-groups', Admin\CardGroupsController::class)->names('groups')->except(['show'])->parameters([
            'card-groups' => 'group'
        ]);
        Route::resource('cards', Admin\CardsController::class)->except(['show']);
        Route::post('cards/{card}/generate-audio', [Admin\CardsController::class, 'generateAudio'])->name('cards.generateAudio');

        Route::prefix('settings')->group(function () {
            Route::get('general', [Admin\SettingsController::class, 'editGeneral'])->name('settings.edit.general');
            Route::put('general', [Admin\SettingsController::class, 'updateGeneral'])->name('settings.update.general');

            Route::get('app', [Admin\SettingsController::class, 'editApp'])->name('settings.edit.app');
            Route::put('app', [Admin\SettingsController::class, 'updateApp'])->name('settings.update.app');
        });

        Route::prefix('records')->group(function () {
            Route::get('unlock', [Admin\UserUnlockRecordsController::class, 'index'])->name('records.unlock');
            Route::get('collect', [Admin\UserCollectRecordsController::class, 'index'])->name('records.collect');
            Route::get('learn', [Admin\UserLearnRecordsController::class, 'index'])->name('records.learn');
            Route::get('subscription', [Admin\UserSubscriptionRecordsController::class, 'index'])->name('records.subscription');
            Route::get('online', [Admin\UserOnlineRecordsController::class, 'index'])->name('records.online');
            Route::get('online/{record}/items', [Admin\UserOnlineRecordsController::class, 'showItems'])->name('records.online.showItems');
        });

        Route::resource('feedback', Admin\FeedbackController::class)->only(['index', 'destroy']);
        Route::get('feedback/{feedback}/replies', [Admin\FeedbackController::class, 'showReplies'])->name('feedback.showReplies');
        Route::post('feedback/{feedback}/replies', [Admin\FeedbackController::class, 'storeReply'])->name('feedback.storeReply');

        Route::resource('abouts', Admin\AboutsController::class)->except(['show']);
        Route::get('abouts/{about}/content', [Admin\AboutsController::class, 'showContent'])->name('abouts.showContent');

        Route::prefix('filepond')->group(function () {
            Route::post('process', [Admin\FilepondUploadsController::class, 'process'])->name('filepond.process');
            Route::get('load', [Admin\FilepondUploadsController::class, 'load'])->name('filepond.load');
            Route::delete('revert', [Admin\FilepondUploadsController::class, 'revert'])->name('filepond.revert');
        });
    });

});

app/Models/Traits/CoverAttribute.php
<?php


namespace App\Models\Traits;


use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

trait CoverAttribute
{
    public function getCoverUrlAttribute()
    {
        $cover = $this->attributes['cover'];
        if(!$cover || Str::startsWith($cover,['http://','https://'])){
            return $cover;
        }
        return Storage::disk('upload')->url($cover);
    }
}

resources/views/admin/groups/create.blade.php
@extends('layouts.admin')
@section('title', '卡片分组添加')

@section('breadcrumb')
  <x-breadcrumb.list>
    <x-breadcrumb.item href="{{ route('admin.dashboard') }}">仪表盘</x-breadcrumb.item>
    <x-breadcrumb.item href="{{ route('admin.groups.index') }}">卡片分组</x-breadcrumb.item>
    <x-breadcrumb.item>添加</x-breadcrumb.item>
  </x-breadcrumb.list>
@endsection

@section('content')
  <div class="flex flex-col rounded shadow-sm bg-white overflow-hidden">
    <div class="py-4 px-5 lg:px-6 flex-grow w-full bg-gray-50">
      <span class="text-gray-900">卡片分组添加</span>
    </div>
    <div class="p-5 lg:p-6 flex-grow w-full">
      <form action="{{ route('admin.groups.store') }}" method="post" class="space-y-6">
        <div hidden>
          @csrf
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="zh_name" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">中文名称</label>
          <input type="text" id="zh_name" name="zh_name" value="{{ old('zh_name') }}" class="block border border-gray-200 rounded px-3 py-2 leading-6 w-full md:w-3/5 focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50" placeholder="请输入中文名称" />
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="en_name" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">英文名称</label>
          <input type="text" id="en_name" name="en_name" value="{{ old('en_name') }}" class="block border border-gray-200 rounded px-3 py-2 leading-6 w-full md:w-3/5 focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50" placeholder="请输入英文名称" />
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="cover" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">封面</label>
          <div class="w-full md:w-3/5" x-data="filepoond()" x-init="() => initFilepond()">
            <input x-ref="filepond-cover" type="file">
            <input type="hidden" name="cover" :value="path">
          </div>
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="cover" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">样式</label>
          <div class="w-full md:w-3/5 space-x-6">
            @foreach(\App\Models\CardGroup::$bgColorMap as $key => $color)
              <label class="inline-flex items-center space-x-2">
                <input id="color" type="radio" name="color" value="{{ $key }}" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" {{ old('color', \App\Models\CardGroup::COLOR_GRAY) == $key ? 'checked' : '' }}>
                <span class="rounded w-5 h-5 {{ $color }}" title="{{ $key }}"></span>
              </label>
            @endforeach
          </div>
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="cover" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">锁定状态</label>
          <div class="w-full md:w-3/5 space-x-6">
            @foreach(\App\Models\CardGroup::$lockStatusMap as $key => $value)
              <label class="inline-flex items-center space-x-2">
                <input id="is_lock" type="radio" name="is_lock" value="{{ $key }}" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" {{ old('is_lock', \App\Models\CardGroup::LOCK_STATUS_UNLOCK) == $key  ? 'checked' : '' }}>
                <span>{{ $value }}</span>
              </label>
            @endforeach
          </div>
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="cover" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">状态</label>
          <div class="w-full md:w-3/5 space-x-6">
            @foreach(\App\Models\CardGroup::$statusMap as $key => $value)
              <label class="inline-flex items-center space-x-2">
                <input id="is_lock" type="radio" name="status" value="{{ $key }}" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" {{ old('status', \App\Models\CardGroup::STATUS_ENABLE) == $key ? 'checked' : '' }}>
                <span>{{ $value }}</span>
              </label>
            @endforeach
          </div>
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="index" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">排序</label>
          <input type="number" id="index" name="index" value="{{ old('index', 99) }}" class="block border border-gray-200 rounded px-3 py-2 leading-6 w-full md:w-3/5 focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50" placeholder="请输入排序" />
        </div>
        <div class="md:w-4/5 ml-auto space-x-2">
          <button type="submit" class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none md:ml-6 px-4 py-2 leading-5 text-sm rounded border-indigo-700 bg-indigo-700 text-white hover:text-white hover:bg-indigo-800 hover:border-indigo-800 focus:ring focus:ring-indigo-500 focus:ring-opacity-50 active:bg-indigo-700 active:border-indigo-700">
            确认
          </button>
          <button type="button" x-on:click="window.history.back()" class="inline-flex justify-center items-center space-x-2 rounded border font-semibold focus:outline-none px-4 py-2 leading-5 text-sm border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
            返回
          </button>
        </div>
      </form>
    </div>
  </div>
@endsection

@push('styles')
  <link rel="stylesheet" href="{{ mix('vendor/filepond/filepond.css') }}">
@endpush

@push('scripts')
  <script src="{{ mix('vendor/filepond/filepond.js') }}"></script>
  <script>
    function filepoond() {
      return {
        path: `{{ old('cover') }}`,
        filepond: null,

        initFilepond() {
          let files = []
          if(this.path) {
            files.push({
              options: {
                type: 'local'
              },
              source: this.path
            })
          }

          FilePond.setOptions({
            server: {
              url: '/admin/filepond',
              process: {
                url: '/process',
                onload: (response) => {
                  this.path = eval('('+response+')');
                  return this.path;
                }
              },
              revert: '/revert',
              restore: '/load?load=',
              load: '/load?load=',
              headers: {
                'X-CSRF-TOKEN': '{{ csrf_token() }}'
              }
            }
          });

          this.filepond = FilePond.create(this.$refs['filepond-cover'], {
            allowMultiple: false,
            maxFiles: 1,
            acceptedFileTypes: 'image/*',
            allowImagePreview: true,
            files
          })
        }
      }
    }
  </script>
@endpush

resources/views/admin/groups/edit.blade.php
@extends('layouts.admin')
@section('title', '卡片分组添加')

@section('breadcrumb')
  <x-breadcrumb.list>
    <x-breadcrumb.item href="{{ route('admin.dashboard') }}">仪表盘</x-breadcrumb.item>
    <x-breadcrumb.item href="{{ route('admin.groups.index') }}">卡片分组</x-breadcrumb.item>
    <x-breadcrumb.item>编辑</x-breadcrumb.item>
  </x-breadcrumb.list>
@endsection

@section('content')
  <div class="flex flex-col rounded shadow-sm bg-white overflow-hidden">
    <div class="py-4 px-5 lg:px-6 flex-grow w-full bg-gray-50">
      <span class="text-gray-900">卡片分组编辑</span>
    </div>
    <div class="p-5 lg:p-6 flex-grow w-full">
      <form action="{{ route('admin.groups.update', $group) }}" method="post" class="space-y-6">
        <div hidden>
          @csrf
          @method('put')
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="zh_name" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">中文名称</label>
          <input type="text" id="zh_name" name="zh_name" value="{{ old('zh_name', $group->zh_name) }}" class="block border border-gray-200 rounded px-3 py-2 leading-6 w-full md:w-3/5 focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50" placeholder="请输入中文名称" />
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="en_name" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">英文名称</label>
          <input type="text" id="en_name" name="en_name" value="{{ old('en_name', $group->en_name) }}" class="block border border-gray-200 rounded px-3 py-2 leading-6 w-full md:w-3/5 focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50" placeholder="请输入英文名称" />
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="cover" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">封面</label>
          <div class="w-full md:w-3/5" x-data="filepoond()" x-init="() => initFilepond()">
            <input x-ref="filepond-cover" type="file">
            <input type="hidden" name="cover" :value="path">
          </div>
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="cover" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">样式</label>
          <div class="w-full md:w-3/5 space-x-6">
            @foreach(\App\Models\CardGroup::$bgColorMap as $key => $color)
              <label class="inline-flex items-center space-x-2">
                <input id="color" type="radio" name="color" value="{{ $key }}" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" {{ $group->color == $key ? 'checked' : '' }}>
                <span class="rounded w-5 h-5 {{ $color }}" title="{{ $key }}"></span>
              </label>
            @endforeach
          </div>
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="cover" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">锁定状态</label>
          <div class="w-full md:w-3/5 space-x-6">
            @foreach(\App\Models\CardGroup::$lockStatusMap as $key => $value)
              <label class="inline-flex items-center space-x-2">
                <input id="is_lock" type="radio" name="is_lock" value="{{ $key }}" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" {{ $group->is_lock === $key ? 'checked' : '' }}>
                <span>{{ $value }}</span>
              </label>
            @endforeach
          </div>
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="cover" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">状态</label>
          <div class="w-full md:w-3/5 space-x-6">
            @foreach(\App\Models\CardGroup::$statusMap as $key => $value)
              <label class="inline-flex items-center space-x-2">
                <input id="status" type="radio" name="status" value="{{ $key }}" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" {{ $group->status === $key ? 'checked' : '' }}>
                <span>{{ $value }}</span>
              </label>
            @endforeach
          </div>
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="index" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">排序</label>
          <input type="number" id="index" name="index" value="{{ old('index', $group->index) }}" class="block border border-gray-200 rounded px-3 py-2 leading-6 w-full md:w-3/5 focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50" placeholder="请输入排序" />
        </div>
        <div class="md:w-4/5 ml-auto space-x-2">
          <button type="submit" class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none md:ml-6 px-4 py-2 leading-5 text-sm rounded border-indigo-700 bg-indigo-700 text-white hover:text-white hover:bg-indigo-800 hover:border-indigo-800 focus:ring focus:ring-indigo-500 focus:ring-opacity-50 active:bg-indigo-700 active:border-indigo-700">
            确认
          </button>
          <button type="button" x-on:click="window.history.back()" class="inline-flex justify-center items-center space-x-2 rounded border font-semibold focus:outline-none px-4 py-2 leading-5 text-sm border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
            返回
          </button>
        </div>
      </form>
    </div>
  </div>
@endsection

@push('styles')
  <link rel="stylesheet" href="{{ mix('vendor/filepond/filepond.css') }}">
@endpush

@push('scripts')
  <script src="{{ mix('vendor/filepond/filepond.js') }}"></script>
  <script>
    function filepoond() {
      return {
        path: `{{ old('cover', $group->cover) }}`,
        filepond: null,

        initFilepond() {
          let files = []
          if(this.path) {
            files.push({
              options: {
                type: 'local'
              },
              source: this.path
            })
          }

          FilePond.setOptions({
            server: {
              url: '/admin/filepond',
              process: {
                url: '/process',
                onload: (response) => {
                  this.path = eval('('+response+')');
                  return this.path;
                }
              },
              revert: '/revert',
              restore: '/load?load=',
              load: '/load?load=',
              headers: {
                'X-CSRF-TOKEN': '{{ csrf_token() }}'
              }
            }
          });

          this.filepond = FilePond.create(this.$refs['filepond-cover'], {
            allowMultiple: false,
            maxFiles: 1,
            acceptedFileTypes: 'image/*',
            allowImagePreview: true,
            files
          })
        }
      }
    }
  </script>
@endpush

resources/views/admin/groups/index.blade.php
@extends('layouts.admin')
@section('title', '卡片分组')

@section('breadcrumb')
  <x-breadcrumb.list>
    <x-breadcrumb.item href="{{ route('admin.dashboard') }}">仪表盘</x-breadcrumb.item>
    <x-breadcrumb.item href="{{ route('admin.groups.index') }}">卡片分组</x-breadcrumb.item>
    <x-breadcrumb.item>列表</x-breadcrumb.item>
  </x-breadcrumb.list>
@endsection

@section('content')
  <div class="flex flex-col rounded shadow-sm bg-white overflow-hidden">
    <div class="py-4 px-5 lg:px-6 flex-grow w-full">
      <form action="{{ route('admin.groups.index') }}" method="get" class="space-y-3 sm:space-y-0 sm:flex sm:items-center sm:space-x-4">
        <div class="flex items-center space-x-1">
          <label for="name" class="flex-shrink-0 text-sm">名称：</label>
          <input type="text" id="name" name="name" value="{{ old('name', request()->name) }}" class="block border border-gray-200 rounded px-3 py-2 leading-5 text-sm w-full focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50" placeholder="名称" />
        </div>
        <div class="flex items-center space-x-1">
          <label for="is_lock" class="flex-shrink-0 text-sm">锁定状态：</label>
          <select id="is_lock" name="is_lock" class="w-24 block border border-gray-200 rounded px-3 py-2 leading-5 text-sm focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50">
            <option value="" {{ is_null(request()->is_lock) ? 'selected' : '' }}>请选择</option>
            <option value="1" {{ request()->is_lock == 1 ? 'selected' : '' }}>免费</option>
            <option value="2" {{ request()->is_lock == 2 ? 'selected' : '' }}>锁定</option>
          </select>
        </div>
        <div class="space-x-2">
          <button type="submit" class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none px-4 py-2 leading-5 text-sm rounded border-indigo-700 bg-indigo-700 text-white hover:text-white hover:bg-indigo-800 hover:border-indigo-800 focus:ring focus:ring-indigo-500 focus:ring-opacity-50 active:bg-indigo-700 active:border-indigo-700">
            <span>搜索</span>
          </button>
          <a href="{{ route('admin.groups.index') }}" class="inline-flex justify-center items-center space-x-2 rounded border font-semibold focus:outline-none px-4 py-2 leading-5 text-sm border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
            <span>清空</span>
          </a>
        </div>
      </form>
    </div>
  </div>
  <div class="flex flex-col rounded shadow-sm bg-white overflow-hidden">
    <div class="p-5 lg:p-6 flex-grow w-full space-y-4">
      <a href="{{ route('admin.groups.create') }}" class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none px-4 py-2 leading-5 text-sm rounded border-indigo-700 bg-indigo-700 text-white hover:text-white hover:bg-indigo-800 hover:border-indigo-800 focus:ring focus:ring-indigo-500 focus:ring-opacity-50 active:bg-indigo-700 active:border-indigo-700">
        <x-heroicon-s-plus class="w-5 h-5 -mx-1" />
        <span>添加</span>
      </a>
      <div class="border border-gray-100 rounded overflow-x-auto min-w-full bg-white">
        <table class="min-w-full text-sm align-middle whitespace-nowrap">
          <thead>
          <tr class="text-gray-700 bg-gray-50 font-semibold">
            <th class="py-3 px-6 text-left">名称</th>
            <th class="py-3 px-6">颜色样式</th>
            <th class="py-3 px-6">卡片总数</th>
            <th class="py-3 px-6">锁定状态</th>
            <th class="py-3 px-6">状态</th>
            <th class="py-3 px-6">创建时间</th>
            <th class="py-3 px-6">操作</th>
          </tr>
          </thead>

          <tbody>
          @if($groups->isNotEmpty())
            @foreach($groups as $group)
              <tr class="border-t border-gray-100">
                <td class="py-3 px-6">
                  <div class="flex items-center space-x-4">
                    @if($group->cover_url)
                      <img src="{{ $group->cover_url }}" alt="{{ $group->zh_name }}" class="inline-block w-10 h-10 rounded-lg" />
                    @endif
                    <div class="flex flex-col">
                      <a href="{{ route('admin.groups.edit', $group) }}" class="text-base text-indigo-600 hover:text-indigo-700 hover:underline">{{ $group->zh_name }}</a>
                      <p class="text-gray-500">{{ $group->en_name }}</p>
                    </div>
                  </div>
                </td>
                <td class="py-3 px-6 text-center">
                  <span class="inline-block rounded w-5 h-5 {{ \App\Models\CardGroup::$bgColorMap[$group->color] }}" title="{{ $group->color }}"></span>
                </td>
                <td class="py-3 px-6 text-center">
                  <a href="{{ route('admin.cards.index', ['group_id' => $group->id]) }}" class="text-base text-indigo-600 hover:text-indigo-700 hover:underline">{{ $group->cards_count }}</a>
                </td>
                <td class="py-3 px-6 text-center">
                  @if($group->is_lock == \App\Models\CardGroup::LOCK_STATUS_UNLOCK)
                    <span class="inline-flex items-center rounded-full py-1 px-2.5 text-sm leading-none text-gray-800 bg-gray-100">免费</span>
                  @else
                    <span class="inline-flex items-center rounded-full py-1 px-2.5 text-sm leading-none text-yellow-800 bg-yellow-100">锁定</span>
                  @endif
                </td>
                <td class="py-3 px-6 text-center">
                  @if($group->status)
                    <span class="inline-flex items-center rounded-full py-1 px-2.5 text-sm leading-none text-green-800 bg-green-100">启用</span>
                  @else
                    <span class="inline-flex items-center rounded-full py-1 px-2.5 text-sm leading-none text-red-800 bg-red-100">禁用</span>
                  @endif
                </td>
                <td class="py-3 px-6 text-center">
                  <span class="text-gray-500">{{ $group->created_at }}</span>
                </td>
                <td class="py-3 px-6 text-center">
                  <a href="{{ route('admin.records.unlock', ['group_id' => $group->id]) }}" class="inline-flex justify-center items-center space-x-1 border font-semibold focus:outline-none px-2 py-1 leading-5 text-sm rounded border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
                    <x-heroicon-s-lock-open  class="w-4 h-4"/>
                    <span>解锁记录</span>
                  </a>
                  <a href="{{ route('admin.groups.edit', $group) }}" class="inline-flex justify-center items-center space-x-1 border font-semibold focus:outline-none px-2 py-1 leading-5 text-sm rounded border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
                    <x-heroicon-s-pencil  class="w-4 h-4"/>
                    <span>编辑</span>
                  </a>
                  <button x-on:click="$dispatch('confirm-delete', { open: true, action: `{{ route('admin.groups.destroy', $group) }}` })" type="button" class="inline-flex justify-center items-center space-x-1 border font-semibold focus:outline-none px-2 py-1 leading-5 text-sm rounded border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
                    <x-heroicon-s-trash  class="w-4 h-4"/>
                    <span>删除</span>
                  </button>
                </td>
              </tr>
            @endforeach
          @else
            <tr class="border-t border-gray-100">
              <td class="py-6 px-6 text-center text-gray-500" colspan="7">暂无数据。</td>
            </tr>
          @endif
          </tbody>
        </table>
      </div>
      <div>
        {{ $groups->withQueryString()->links('partials.admin.pagination') }}
      </div>
    </div>
  </div>
  <x-dialog.confirm-delete>
    <p class="text-gray-600">是否删除该卡片分组？</p>
  </x-dialog.confirm-delete>
@endsection