routes/web.php
<?php

use App\Http\Controllers\Admin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
})->name('home');

Route::prefix('admin')->as('admin.')->middleware('guard:admin')->group(function () {


    Route::middleware('admin.guest')->group(function () {

        Route::get('login', [Admin\AuthenticatedSessionController::class, 'create'])->name('login');
        Route::post('login', [Admin\AuthenticatedSessionController::class, 'store']);

    });

    Route::middleware('admin.auth')->group(function () {

        Route::post('/logout', [Admin\AuthenticatedSessionController::class, 'destroy'])->name('logout');

        Route::get('/profile', [Admin\HomeController::class, 'showProfileForm'])->name('profile');
        Route::post('/profile', [Admin\HomeController::class, 'updateProfile'])->name('profile.update');

        Route::get('/', [Admin\HomeController::class, 'dashboard'])->name('dashboard');

        Route::resource('users', Admin\UsersController::class)->except(['create', 'store', 'show']);
        Route::post('users/{user}/renew', [Admin\UsersController::class, 'renew'])->name('users.renew');
        Route::resource('plans', Admin\PlansController::class)->except(['show']);
        Route::resource('card-groups', Admin\CardGroupsController::class)->names('groups')->except(['show'])->parameters([
            'card-groups' => 'group'
        ]);
        Route::resource('cards', Admin\CardsController::class)->except(['show']);
        Route::post('cards/{card}/generate-audio', [Admin\CardsController::class, 'generateAudio'])->name('cards.generateAudio');

        Route::prefix('settings')->group(function () {
            Route::get('general', [Admin\SettingsController::class, 'editGeneral'])->name('settings.edit.general');
            Route::put('general', [Admin\SettingsController::class, 'updateGeneral'])->name('settings.update.general');

            Route::get('app', [Admin\SettingsController::class, 'editApp'])->name('settings.edit.app');
            Route::put('app', [Admin\SettingsController::class, 'updateApp'])->name('settings.update.app');
        });

        Route::prefix('records')->group(function () {
            Route::get('unlock', [Admin\UserUnlockRecordsController::class, 'index'])->name('records.unlock');
            Route::get('collect', [Admin\UserCollectRecordsController::class, 'index'])->name('records.collect');
            Route::get('learn', [Admin\UserLearnRecordsController::class, 'index'])->name('records.learn');
            Route::get('subscription', [Admin\UserSubscriptionRecordsController::class, 'index'])->name('records.subscription');
            Route::get('online', [Admin\UserOnlineRecordsController::class, 'index'])->name('records.online');
            Route::get('online/{record}/items', [Admin\UserOnlineRecordsController::class, 'showItems'])->name('records.online.showItems');
        });

        Route::resource('feedback', Admin\FeedbackController::class)->only(['index', 'destroy']);
        Route::get('feedback/{feedback}/replies', [Admin\FeedbackController::class, 'showReplies'])->name('feedback.showReplies');
        Route::post('feedback/{feedback}/replies', [Admin\FeedbackController::class, 'storeReply'])->name('feedback.storeReply');

        Route::resource('abouts', Admin\AboutsController::class)->except(['show']);
        Route::get('abouts/{about}/content', [Admin\AboutsController::class, 'showContent'])->name('abouts.showContent');

        Route::prefix('filepond')->group(function () {
            Route::post('process', [Admin\FilepondUploadsController::class, 'process'])->name('filepond.process');
            Route::get('load', [Admin\FilepondUploadsController::class, 'load'])->name('filepond.load');
            Route::delete('revert', [Admin\FilepondUploadsController::class, 'revert'])->name('filepond.revert');
        });
    });

});

app/Models/Plan.php
<?php

namespace App\Models;

use App\Models\Traits\OrderIndexScope;
use App\Models\Traits\StatusScope;
use EloquentFilter\Filterable;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Plan extends Model
{
    use HasFactory, StatusScope, OrderIndexScope, Filterable;

    const INTERVAL_DAY = 'day';
    const INTERVAL_MONTH = 'month';
    const INTERVAL_YEAR = 'year';
    public static $intervalMap = [
        self::INTERVAL_DAY => '天',
        self::INTERVAL_MONTH => '个月',
        self::INTERVAL_YEAR => '年',
    ];

    const TAG_RECOMMEND = 'recommend';
    const TAG_LIMIT = 'limit';
    public static $tagMap = [
        self::TAG_RECOMMEND => '推荐',
        self::TAG_LIMIT => '限时',
    ];

    const STATUS_ENABLE = 1;
    const STATUS_DISABLE = 0;
    public static $statusMap = [
        self::STATUS_ENABLE => '启用',
        self::STATUS_DISABLE => '禁用',
    ];

    const INFINITE_VALUE = -1;
    const INFINITE_TIME = '9999-12-31 23:59:59';


    protected $fillable = [
        'name',
        'price',
        'period',
        'interval',
        'description',
        'tag',
        'status',
        'index',
    ];

    protected $casts = [
        'price' => 'float',
        'status' => 'boolean',
    ];

    // 是否永久
    public function isInfinite()
    {
        return $this->getAttribute('period') === self::INFINITE_VALUE;
    }

    public function getIntervalTextAttribute()
    {
        return self::$intervalMap[$this->getAttribute('interval')] ?? '未知周期';
    }
}

resources/views/admin/records/collect.blade.php
@extends('layouts.admin')
@section('title', '收藏记录')

@section('breadcrumb')
  <x-breadcrumb.list>
    <x-breadcrumb.item href="{{ route('admin.dashboard') }}">仪表盘</x-breadcrumb.item>
    <x-breadcrumb.item href="javascript:;">统计报告</x-breadcrumb.item>
    <x-breadcrumb.item href="{{ route('admin.records.collect') }}">收藏记录</x-breadcrumb.item>
    <x-breadcrumb.item>列表</x-breadcrumb.item>
  </x-breadcrumb.list>
@endsection

@section('content')
  <div class="flex flex-col rounded shadow-sm bg-white overflow-hidden">
    <div class="py-4 px-5 lg:px-6 flex-grow w-full">
      <form action="{{ route('admin.records.collect') }}" method="get" class="space-y-3 sm:space-y-0 sm:flex sm:items-center sm:space-x-4">
        <div class="flex items-center space-x-1">
          <label for="user_id" class="flex-shrink-0 text-sm">用户：</label>
          <select id="user_id" name="user_id" class="w-28 block border border-gray-200 rounded px-3 py-2 leading-5 text-sm focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50">
            <option value="" {{ is_null(request()->user_id) ? 'selected' : '' }}>请选择</option>
            @foreach($filterUsers as $user)
              <option value="{{ $user->id }}" {{ request()->user_id == $user->id ? 'selected' : '' }}>{{ $user->name }}</option>
            @endforeach
          </select>
        </div>
        <div class="flex items-center space-x-1">
          <label for="card_id" class="flex-shrink-0 text-sm">卡片：</label>
          <select id="card_id" name="card_id" class="w-28 block border border-gray-200 rounded px-3 py-2 leading-5 text-sm focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50">
            <option value="" {{ is_null(request()->card_id) ? 'selected' : '' }}>请选择</option>
            @foreach($groups as $group)
              <optgroup label="{{ $group->zh_name }}">
                @foreach($group->cards as $card)
                  <option value="{{ $card->id }}" {{ request()->card_id == $card->id ? 'selected' : '' }}>{{ $card->zh_name }}</option>
                @endforeach
              </optgroup>
            @endforeach
          </select>
        </div>
        <div class="space-x-2">
          <button type="submit" class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none px-4 py-2 leading-5 text-sm rounded border-indigo-700 bg-indigo-700 text-white hover:text-white hover:bg-indigo-800 hover:border-indigo-800 focus:ring focus:ring-indigo-500 focus:ring-opacity-50 active:bg-indigo-700 active:border-indigo-700">
            <span>搜索</span>
          </button>
          <a href="{{ route('admin.records.collect') }}" class="inline-flex justify-center items-center space-x-2 rounded border font-semibold focus:outline-none px-4 py-2 leading-5 text-sm border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
            <span>清空</span>
          </a>
        </div>
      </form>
    </div>
  </div>
  <div class="flex flex-col rounded shadow-sm bg-white overflow-hidden">
    <div class="p-5 lg:p-6 flex-grow w-full space-y-4">
      <div class="border border-gray-100 rounded overflow-x-auto min-w-full bg-white">
        <table class="min-w-full text-sm align-middle whitespace-nowrap">
          <thead>
          <tr class="text-gray-700 bg-gray-50 font-semibold">
            <th class="py-3 px-6 text-left">用户</th>
            <th class="py-3 px-6">卡片分组</th>
            <th class="py-3 px-6">卡片</th>
            <th class="py-3 px-6">收藏时间</th>
          </tr>
          </thead>

          <tbody>
          @if($records->isNotEmpty())
            @foreach($records as $record)
              <tr class="border-t border-gray-100">
                <td class="py-3 px-6">
                  <div class="flex items-center space-x-3">
                    <img src="{{ $record->user->avatar }}" alt="{{ $record->user->name }}" class="inline-block w-8 h-8 rounded-full" />
                    <div class="flex flex-col">
                      <h3 class="text-gray-900 text-base font-medium">{{ $record->user->name }}</h3>
                    </div>
                  </div>
                </td>
                <td class="py-3 px-6 text-center">
                  <a href="{{ route('admin.groups.edit', $record->group) }}" class="text-base text-indigo-600 hover:text-indigo-700 hover:underline">{{ $record->group->zh_name }}</a>
                </td>
                <td class="py-3 px-6 text-center">
                  <a href="{{ route('admin.cards.edit', $record->card) }}" class="text-base text-indigo-600 hover:text-indigo-700 hover:underline">{{ $record->card->zh_name }}</a>
                </td>
                <td class="py-3 px-6 text-center">
                  <span class="text-gray-500">{{ $record->created_at }}</span>
                </td>
              </tr>
            @endforeach
          @else
            <tr class="border-t border-gray-100">
              <td class="py-6 px-6 text-center text-gray-500" colspan="4">暂无数据。</td>
            </tr>
          @endif
          </tbody>
        </table>
      </div>
      <div>
        {{ $records->withQueryString()->links('partials.admin.pagination') }}
      </div>
    </div>
  </div>
@endsection

resources/views/admin/records/learn.blade.php
@extends('layouts.admin')
@section('title', '卡片学习记录')

@section('breadcrumb')
  <x-breadcrumb.list>
    <x-breadcrumb.item href="{{ route('admin.dashboard') }}">仪表盘</x-breadcrumb.item>
    <x-breadcrumb.item href="javascript:;">统计报告</x-breadcrumb.item>
    <x-breadcrumb.item href="{{ route('admin.records.learn') }}">卡片学习记录</x-breadcrumb.item>
    <x-breadcrumb.item>列表</x-breadcrumb.item>
  </x-breadcrumb.list>
@endsection

@section('content')
  <div class="flex flex-col rounded shadow-sm bg-white overflow-hidden">
    <div class="py-4 px-5 lg:px-6 flex-grow w-full">
      <form action="{{ route('admin.records.learn') }}" method="get" class="space-y-3 sm:space-y-0 sm:flex sm:items-center sm:space-x-4">
        <div class="flex items-center space-x-1">
          <label for="user_id" class="flex-shrink-0 text-sm">用户：</label>
          <select id="user_id" name="user_id" class="w-28 block border border-gray-200 rounded px-3 py-2 leading-5 text-sm focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50">
            <option value="" {{ is_null(request()->user_id) ? 'selected' : '' }}>请选择</option>
            @foreach($filterUsers as $user)
              <option value="{{ $user->id }}" {{ request()->user_id == $user->id ? 'selected' : '' }}>{{ $user->name }}</option>
            @endforeach
          </select>
        </div>
        <div class="flex items-center space-x-1">
          <label for="card_id" class="flex-shrink-0 text-sm">卡片：</label>
          <select id="card_id" name="card_id" class="w-28 block border border-gray-200 rounded px-3 py-2 leading-5 text-sm focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50">
            <option value="" {{ is_null(request()->card_id) ? 'selected' : '' }}>请选择</option>
            @foreach($groups as $group)
              <optgroup label="{{ $group->zh_name }}">
                @foreach($group->cards as $card)
                  <option value="{{ $card->id }}" {{ request()->card_id == $card->id ? 'selected' : '' }}>{{ $card->zh_name }}</option>
                @endforeach
              </optgroup>
            @endforeach
          </select>
        </div>
        <div class="space-x-2">
          <button type="submit" class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none px-4 py-2 leading-5 text-sm rounded border-indigo-700 bg-indigo-700 text-white hover:text-white hover:bg-indigo-800 hover:border-indigo-800 focus:ring focus:ring-indigo-500 focus:ring-opacity-50 active:bg-indigo-700 active:border-indigo-700">
            <span>搜索</span>
          </button>
          <a href="{{ route('admin.records.learn') }}" class="inline-flex justify-center items-center space-x-2 rounded border font-semibold focus:outline-none px-4 py-2 leading-5 text-sm border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
            <span>清空</span>
          </a>
        </div>
      </form>
    </div>
  </div>
  <div class="flex flex-col rounded shadow-sm bg-white overflow-hidden">
    <div class="p-5 lg:p-6 flex-grow w-full space-y-4">
      <div class="border border-gray-100 rounded overflow-x-auto min-w-full bg-white">
        <table class="min-w-full text-sm align-middle whitespace-nowrap">
          <thead>
          <tr class="text-gray-700 bg-gray-50 font-semibold">
            <th class="py-3 px-6 text-left">用户</th>
            <th class="py-3 px-6">卡片分组</th>
            <th class="py-3 px-6">卡片</th>
            <th class="py-3 px-6">学习时间</th>
          </tr>
          </thead>

          <tbody>
          @if($records->isNotEmpty())
            @foreach($records as $record)
              <tr class="border-t border-gray-100">
                <td class="py-3 px-6">
                  <div class="flex items-center space-x-3">
                    <img src="{{ $record->user->avatar }}" alt="{{ $record->user->name }}" class="inline-block w-8 h-8 rounded-full" />
                    <div class="flex flex-col">
                      <h3 class="text-gray-900 text-base font-medium">{{ $record->user->name }}</h3>
                    </div>
                  </div>
                </td>
                <td class="py-3 px-6 text-center">
                  <a href="{{ route('admin.groups.edit', $record->group) }}" class="text-base text-indigo-600 hover:text-indigo-700 hover:underline">{{ $record->group->zh_name }}</a>
                </td>
                <td class="py-3 px-6 text-center">
                  <a href="{{ route('admin.cards.edit', $record->card) }}" class="text-base text-indigo-600 hover:text-indigo-700 hover:underline">{{ $record->card->zh_name }}</a>
                </td>
                <td class="py-3 px-6 text-center">
                  <span class="text-gray-500">{{ $record->created_at }}</span>
                </td>
              </tr>
            @endforeach
          @else
            <tr class="border-t border-gray-100">
              <td class="py-6 px-6 text-center text-gray-500" colspan="4">暂无数据。</td>
            </tr>
          @endif
          </tbody>
        </table>
      </div>
      <div>
        {{ $records->withQueryString()->links('partials.admin.pagination') }}
      </div>
    </div>
  </div>
@endsection

resources/views/admin/records/subscription.blade.php
@extends('layouts.admin')
@section('title', '会员订阅记录')

@section('breadcrumb')
  <x-breadcrumb.list>
    <x-breadcrumb.item href="{{ route('admin.dashboard') }}">仪表盘</x-breadcrumb.item>
    <x-breadcrumb.item href="javascript:;">统计报告</x-breadcrumb.item>
    <x-breadcrumb.item href="{{ route('admin.records.subscription') }}">会员订阅记录</x-breadcrumb.item>
    <x-breadcrumb.item>列表</x-breadcrumb.item>
  </x-breadcrumb.list>
@endsection

@section('content')
  <div class="flex flex-col rounded shadow-sm bg-white overflow-hidden">
    <div class="py-4 px-5 lg:px-6 flex-grow w-full">
      <form action="{{ route('admin.records.subscription') }}" method="get" class="space-y-3 sm:space-y-0 sm:flex sm:items-center sm:space-x-4">
        <div class="flex items-center space-x-1">
          <label for="user_id" class="flex-shrink-0 text-sm">用户：</label>
          <select id="user_id" name="user_id" class="w-28 block border border-gray-200 rounded px-3 py-2 leading-5 text-sm focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50">
            <option value="" {{ is_null(request()->user_id) ? 'selected' : '' }}>请选择</option>
            @foreach($filterUsers as $user)
              <option value="{{ $user->id }}" {{ request()->user_id == $user->id ? 'selected' : '' }}>{{ $user->name }}</option>
            @endforeach
          </select>
        </div>
        <div class="flex items-center space-x-1">
          <label for="plan_id" class="flex-shrink-0 text-sm">方案：</label>
          <select id="plan_id" name="plan_id" class="w-28 block border border-gray-200 rounded px-3 py-2 leading-5 text-sm focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50">
            <option value="" {{ is_null(request()->plan_id) ? 'selected' : '' }}>请选择</option>
            @foreach($plans as $plan)
              <option value="{{ $plan->id }}" {{ request()->plan_id == $plan->id ? 'selected' : '' }}>{{ $plan->name }}</option>
            @endforeach
          </select>
        </div>
        <div class="space-x-2">
          <button type="submit" class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none px-4 py-2 leading-5 text-sm rounded border-indigo-700 bg-indigo-700 text-white hover:text-white hover:bg-indigo-800 hover:border-indigo-800 focus:ring focus:ring-indigo-500 focus:ring-opacity-50 active:bg-indigo-700 active:border-indigo-700">
            <span>搜索</span>
          </button>
          <a href="{{ route('admin.records.subscription') }}" class="inline-flex justify-center items-center space-x-2 rounded border font-semibold focus:outline-none px-4 py-2 leading-5 text-sm border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
            <span>清空</span>
          </a>
        </div>
      </form>
    </div>
  </div>
  <div class="flex flex-col rounded shadow-sm bg-white overflow-hidden">
    <div class="p-5 lg:p-6 flex-grow w-full space-y-4">
      <div class="border border-gray-100 rounded overflow-x-auto min-w-full bg-white">
        <table class="min-w-full text-sm align-middle whitespace-nowrap">
          <thead>
          <tr class="text-gray-700 bg-gray-50 font-semibold">
            <th class="py-3 px-6 text-left">用户</th>
            <th class="py-3 px-6">方案</th>
            <th class="py-3 px-6">金额</th>
            <th class="py-3 px-6">时长</th>
            <th class="py-3 px-6">支付时间</th>
            <th class="py-3 px-6">创建时间</th>
          </tr>
          </thead>

          <tbody>
          @if($records->isNotEmpty())
            @foreach($records as $record)
              <tr class="border-t border-gray-100">
                <td class="py-3 px-6">
                  <div class="flex items-center space-x-3">
                    <img src="{{ $record->user->avatar }}" alt="{{ $record->user->name }}" class="inline-block w-8 h-8 rounded-full" />
                    <div class="flex flex-col">
                      <h3 class="text-gray-900 text-base font-medium">{{ $record->user->name }}</h3>
                    </div>
                  </div>
                </td>
                <td class="py-3 px-6 text-center">
                  <a href="{{ route('admin.plans.edit', $record->plan) }}" class="text-base text-indigo-600 hover:text-indigo-700 hover:underline">{{ $record->plan->name }}</a>
                </td>
                <td class="py-3 px-6 text-center">
                  <span class="text-red-600">￥{{ $record->amount }}</span>
                </td>
                <td class="py-3 px-6 text-center">
                  @if($record->period === \App\Models\Plan::INFINITE_VALUE)
                    <span class="inline-flex items-center rounded-full py-1 px-2.5 text-sm leading-none text-yellow-800 bg-yellow-100">永久</span>
                  @else
                    <span class="font-semibold">{{ $record->period }}</span>
                    <span>{{ $record->interval_text }}</span>
                  @endif
                </td>
                <td class="py-3 px-6 text-center">
                  @if(is_null($record->paid_at))
                    <span class="inline-flex items-center rounded-full py-1 px-2.5 text-sm leading-none text-gray-800 bg-gray-100">未支付</span>
                  @else
                    <span class="text-gray-500">{{ $record->paid_at }}</span>
                  @endif
                </td>
                <td class="py-3 px-6 text-center">
                  <span class="text-gray-500">{{ $record->created_at }}</span>
                </td>
              </tr>
            @endforeach
          @else
            <tr class="border-t border-gray-100">
              <td class="py-6 px-6 text-center text-gray-500" colspan="6">暂无数据。</td>
            </tr>
          @endif
          </tbody>
        </table>
      </div>
      <div>
        {{ $records->withQueryString()->links('partials.admin.pagination') }}
      </div>
    </div>
  </div>
@endsection

resources/views/admin/records/unlock.blade.php
@extends('layouts.admin')
@section('title', '卡组解锁记录')

@section('breadcrumb')
  <x-breadcrumb.list>
    <x-breadcrumb.item href="{{ route('admin.dashboard') }}">仪表盘</x-breadcrumb.item>
    <x-breadcrumb.item href="javascript:;">统计报告</x-breadcrumb.item>
    <x-breadcrumb.item href="{{ route('admin.records.unlock') }}">卡组解锁记录</x-breadcrumb.item>
    <x-breadcrumb.item>列表</x-breadcrumb.item>
  </x-breadcrumb.list>
@endsection

@section('content')
  <div class="flex flex-col rounded shadow-sm bg-white overflow-hidden">
    <div class="py-4 px-5 lg:px-6 flex-grow w-full">
      <form action="{{ route('admin.records.unlock') }}" method="get" class="space-y-3 sm:space-y-0 sm:flex sm:items-center sm:space-x-4">
        <div class="flex items-center space-x-1">
          <label for="user_id" class="flex-shrink-0 text-sm">用户：</label>
          <select id="user_id" name="user_id" class="w-28 block border border-gray-200 rounded px-3 py-2 leading-5 text-sm focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50">
            <option value="" {{ is_null(request()->user_id) ? 'selected' : '' }}>请选择</option>
            @foreach($filterUsers as $user)
              <option value="{{ $user->id }}" {{ request()->user_id == $user->id ? 'selected' : '' }}>{{ $user->name }}</option>
            @endforeach
          </select>
        </div>
        <div class="flex items-center space-x-1">
          <label for="card_id" class="flex-shrink-0 text-sm">卡组：</label>
          <select id="card_id" name="card_id" class="w-28 block border border-gray-200 rounded px-3 py-2 leading-5 text-sm focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50">
            <option value="" {{ is_null(request()->group_id) ? 'selected' : '' }}>请选择</option>
            @foreach($groups as $group)
              <option value="{{ $group->id }}" {{ request()->group_id == $group->id ? 'selected' : '' }}>{{ $group->zh_name }}</option>
            @endforeach
          </select>
        </div>
        <div class="space-x-2">
          <button type="submit" class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none px-4 py-2 leading-5 text-sm rounded border-indigo-700 bg-indigo-700 text-white hover:text-white hover:bg-indigo-800 hover:border-indigo-800 focus:ring focus:ring-indigo-500 focus:ring-opacity-50 active:bg-indigo-700 active:border-indigo-700">
            <span>搜索</span>
          </button>
          <a href="{{ route('admin.records.unlock') }}" class="inline-flex justify-center items-center space-x-2 rounded border font-semibold focus:outline-none px-4 py-2 leading-5 text-sm border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
            <span>清空</span>
          </a>
        </div>
      </form>
    </div>
  </div>
  <div class="flex flex-col rounded shadow-sm bg-white overflow-hidden">
    <div class="p-5 lg:p-6 flex-grow w-full space-y-4">
      <div class="border border-gray-100 rounded overflow-x-auto min-w-full bg-white">
        <table class="min-w-full text-sm align-middle whitespace-nowrap">
          <thead>
          <tr class="text-gray-700 bg-gray-50 font-semibold">
            <th class="py-3 px-6 text-left">用户</th>
            <th class="py-3 px-6">卡片</th>
            <th class="py-3 px-6">解锁时间</th>
            <th class="py-3 px-6">到期时间</th>
          </tr>
          </thead>

          <tbody>
          @if($records->isNotEmpty())
            @foreach($records as $record)
              <tr class="border-t border-gray-100">
                <td class="py-3 px-6">
                  <div class="flex items-center space-x-3">
                    <img src="{{ $record->user->avatar }}" alt="{{ $record->user->name }}" class="inline-block w-8 h-8 rounded-full" />
                    <div class="flex flex-col">
                      <h3 class="text-gray-900 text-base font-medium">{{ $record->user->name }}</h3>
                    </div>
                  </div>
                </td>
                <td class="py-3 px-6 text-center">
                  <a href="{{ route('admin.groups.edit', $record->group) }}" class="text-base text-indigo-600 hover:text-indigo-700 hover:underline">{{ $record->group->zh_name }}</a>
                </td>
                <td class="py-3 px-6 text-center">
                  <span class="text-gray-500">{{ $record->created_at }}</span>
                </td>
                <td class="py-3 px-6 text-center">
                  <span class="text-gray-500">{{ $record->expired_at }}</span>
                </td>
              </tr>
            @endforeach
          @else
            <tr class="border-t border-gray-100">
              <td class="py-6 px-6 text-center text-gray-500" colspan="4">暂无数据。</td>
            </tr>
          @endif
          </tbody>
        </table>
      </div>
      <div>
        {{ $records->withQueryString()->links('partials.admin.pagination') }}
      </div>
    </div>
  </div>
@endsection