routes/web.php
<?php

use App\Http\Controllers\Admin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
})->name('home');

Route::prefix('admin')->as('admin.')->middleware('guard:admin')->group(function () {


    Route::middleware('admin.guest')->group(function () {

        Route::get('login', [Admin\AuthenticatedSessionController::class, 'create'])->name('login');
        Route::post('login', [Admin\AuthenticatedSessionController::class, 'store']);

    });

    Route::middleware('admin.auth')->group(function () {

        Route::post('/logout', [Admin\AuthenticatedSessionController::class, 'destroy'])->name('logout');

        Route::get('/profile', [Admin\HomeController::class, 'showProfileForm'])->name('profile');
        Route::post('/profile', [Admin\HomeController::class, 'updateProfile'])->name('profile.update');

        Route::get('/', [Admin\HomeController::class, 'dashboard'])->name('dashboard');

        Route::resource('users', Admin\UsersController::class)->except(['create', 'store', 'show']);
        Route::post('users/{user}/renew', [Admin\UsersController::class, 'renew'])->name('users.renew');
        Route::resource('plans', Admin\PlansController::class)->except(['show']);
        Route::resource('card-groups', Admin\CardGroupsController::class)->names('groups')->except(['show'])->parameters([
            'card-groups' => 'group'
        ]);
        Route::resource('cards', Admin\CardsController::class)->except(['show']);
        Route::post('cards/{card}/generate-audio', [Admin\CardsController::class, 'generateAudio'])->name('cards.generateAudio');

        Route::prefix('settings')->group(function () {
            Route::get('general', [Admin\SettingsController::class, 'editGeneral'])->name('settings.edit.general');
            Route::put('general', [Admin\SettingsController::class, 'updateGeneral'])->name('settings.update.general');

            Route::get('app', [Admin\SettingsController::class, 'editApp'])->name('settings.edit.app');
            Route::put('app', [Admin\SettingsController::class, 'updateApp'])->name('settings.update.app');
        });

        Route::prefix('records')->group(function () {
            Route::get('unlock', [Admin\UserUnlockRecordsController::class, 'index'])->name('records.unlock');
            Route::get('collect', [Admin\UserCollectRecordsController::class, 'index'])->name('records.collect');
            Route::get('learn', [Admin\UserLearnRecordsController::class, 'index'])->name('records.learn');
            Route::get('subscription', [Admin\UserSubscriptionRecordsController::class, 'index'])->name('records.subscription');
            Route::get('online', [Admin\UserOnlineRecordsController::class, 'index'])->name('records.online');
            Route::get('online/{record}/items', [Admin\UserOnlineRecordsController::class, 'showItems'])->name('records.online.showItems');
        });

        Route::resource('feedback', Admin\FeedbackController::class)->only(['index', 'destroy']);
        Route::get('feedback/{feedback}/replies', [Admin\FeedbackController::class, 'showReplies'])->name('feedback.showReplies');
        Route::post('feedback/{feedback}/replies', [Admin\FeedbackController::class, 'storeReply'])->name('feedback.storeReply');

        Route::resource('abouts', Admin\AboutsController::class)->except(['show']);
        Route::get('abouts/{about}/content', [Admin\AboutsController::class, 'showContent'])->name('abouts.showContent');

        Route::prefix('filepond')->group(function () {
            Route::post('process', [Admin\FilepondUploadsController::class, 'process'])->name('filepond.process');
            Route::get('load', [Admin\FilepondUploadsController::class, 'load'])->name('filepond.load');
            Route::delete('revert', [Admin\FilepondUploadsController::class, 'revert'])->name('filepond.revert');
        });
    });

});

app/Models/About.php
<?php

namespace App\Models;

use EloquentFilter\Filterable;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class About extends Model
{
    use HasFactory, Filterable;

    const STATUS_ENABLE = 1;
    const STATUS_DISABLE = 0;
    public static $statusMap = [
        self::STATUS_ENABLE => '启用',
        self::STATUS_DISABLE => '禁用',
    ];

    protected $fillable = [
        'name',
        'key',
        'content',
        'status',
    ];
}

app/Http/Controllers/Admin/AboutsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\AboutRequest;
use App\ModelFilters\Admin\AboutFilter;
use App\Models\About;
use Illuminate\Http\Request;

class AboutsController extends Controller
{
    public function index(Request $request)
    {
        $abouts = About::filter($request->all(), AboutFilter::class)->latest()->paginate();

        return view('admin.abouts.index', compact('abouts'));
    }

    public function create()
    {
        return view('admin.abouts.create');
    }

    public function store(AboutRequest $request)
    {
        About::create($request->only([
            'name',
            'key',
            'content',
            'status',
        ]));

        return redirect()->route('admin.abouts.index')->with('success', '添加内容成功！');
    }

    public function edit(About $about)
    {
        return view('admin.abouts.edit',  compact('about'));
    }

    public function update(AboutRequest $request, About $about)
    {
        $about->fill($request->only([
            'name',
            'key',
            'content',
            'status',
        ]));
        $about->save();

        return back()->with('success', '修改内容成功！');
    }

    public function destroy(About $about)
    {
        $about->delete();

        return back()->with('success', '删除内容成功！');
    }

    public function showContent(Request $request, About $about)
    {
        return view('admin.abouts.show-content', compact('about'));
    }
}

app/Http/Controllers/Api/AboutsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\AboutResource;
use App\Models\About;
use Illuminate\Http\Request;

class AboutsController extends Controller
{
    public function show(About $about)
    {
        return AboutResource::make($about);
    }
}

resources/views/admin/abouts/create.blade.php
@extends('layouts.admin')
@section('title', '关于我们添加')

@section('breadcrumb')
  <x-breadcrumb.list>
    <x-breadcrumb.item href="{{ route('admin.dashboard') }}">仪表盘</x-breadcrumb.item>
    <x-breadcrumb.item href="{{ route('admin.abouts.index') }}">关于我们</x-breadcrumb.item>
    <x-breadcrumb.item>添加</x-breadcrumb.item>
  </x-breadcrumb.list>
@endsection

@section('content')
  <div class="flex flex-col rounded shadow-sm bg-white overflow-hidden">
    <div class="py-4 px-5 lg:px-6 flex-grow w-full bg-gray-50">
      <span class="text-gray-900">关于我们添加</span>
    </div>
    <div class="p-5 lg:p-6 flex-grow w-full">
      <form action="{{ route('admin.abouts.store') }}" method="post" class="space-y-6">
        <div hidden>
          @csrf
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="name" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">名称</label>
          <input type="text" id="name" name="name" value="{{ old('name') }}" class="block border border-gray-200 rounded px-3 py-2 leading-6 w-full md:w-3/5 focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50" placeholder="请输入名称" />
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="key" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">标识</label>
          <input type="text" id="key" name="key" value="{{ old('key') }}" class="block border border-gray-200 rounded px-3 py-2 leading-6 w-full md:w-3/5 focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50" placeholder="请输入标识" />
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-baseline" x-data="quillEditor(`{{ old('content', '') }}`)" x-init="init()">
          <label for="content" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">主要内容</label>
          <div class="md:w-3/5">
            <input type="hidden" id="content" name="content" x-model.debounce="content">
            <div x-ref="quillEditor" class="bg-white">
              {!! old('content', '') !!}
            </div>
          </div>
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="cover" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">状态</label>
          <div class="w-full md:w-3/5 space-x-6">
            @foreach(\App\Models\Card::$statusMap as $key => $value)
              <label class="inline-flex items-center space-x-2">
                <input id="status" type="radio" name="status" value="{{ $key }}" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" {{ old('status', \App\Models\CardGroup::STATUS_ENABLE) == $key ? 'checked' : '' }}>
                <span>{{ $value }}</span>
              </label>
            @endforeach
          </div>
        </div>
        <div class="md:w-4/5 ml-auto space-x-2">
          <button type="submit" class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none md:ml-6 px-4 py-2 leading-5 text-sm rounded border-indigo-700 bg-indigo-700 text-white hover:text-white hover:bg-indigo-800 hover:border-indigo-800 focus:ring focus:ring-indigo-500 focus:ring-opacity-50 active:bg-indigo-700 active:border-indigo-700">
            确认
          </button>
          <button type="button" x-on:click="window.history.back()" class="inline-flex justify-center items-center space-x-2 rounded border font-semibold focus:outline-none px-4 py-2 leading-5 text-sm border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
            返回
          </button>
        </div>
      </form>
    </div>
  </div>
@endsection

@push('styles')
  <link rel="stylesheet" href="{{ mix('vendor/quill/quill.css') }}">
@endpush

@push('beforeScripts')
  <script src="{{ mix('vendor/quill/quill.js') }}"></script>
@endpush

@push('scripts')
  <script>
    function quillEditor(content) {
      return {
        content: content,

        init() {
          let that = this
          quill = new Quill(this.$refs.quillEditor, {
            modules: {
              toolbar: {
                container: [
                  [{ 'size': ['small', false, 'large', 'huge'] }],
                  [{'header': 2}, {'header': 3}],
                  ['bold', 'italic', 'underline', 'strike'],
                  ['link', 'blockquote', 'code-block', 'image'],
                  [{ list: 'ordered' }, { list: 'bullet' }, { 'align': [false, 'center', 'right', 'justify']}]
                ]
              }
            },
            theme: 'snow',
            scrollingContainer: 'html, body',
            placeholder: '请输入内容'
          })
          quill.on('text-change', function () {
            that.content = quill.getText() ? quill.root.innerHTML : ''
          })
        }
      }
    }
  </script>
@endpush

resources/views/admin/abouts/edit.blade.php
@extends('layouts.admin')
@section('title', '关于我们编辑')

@section('breadcrumb')
  <x-breadcrumb.list>
    <x-breadcrumb.item href="{{ route('admin.dashboard') }}">仪表盘</x-breadcrumb.item>
    <x-breadcrumb.item href="{{ route('admin.abouts.index') }}">关于我们</x-breadcrumb.item>
    <x-breadcrumb.item>编辑</x-breadcrumb.item>
  </x-breadcrumb.list>
@endsection

@section('content')
  <div class="flex flex-col rounded shadow-sm bg-white overflow-hidden">
    <div class="py-4 px-5 lg:px-6 flex-grow w-full bg-gray-50">
      <span class="text-gray-900">关于我们编辑</span>
    </div>
    <div class="p-5 lg:p-6 flex-grow w-full">
      <form action="{{ route('admin.abouts.update', $about) }}" method="post" class="space-y-6">
        <div hidden>
          @csrf
          @method('put')
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="name" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">名称</label>
          <input type="text" id="name" name="name" value="{{ old('name', $about->name) }}" class="block border border-gray-200 rounded px-3 py-2 leading-6 w-full md:w-3/5 focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50" placeholder="请输入名称" />
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="key" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">标识</label>
          <input type="text" id="key" name="key" value="{{ old('key', $about->key) }}" class="block border border-gray-200 rounded px-3 py-2 leading-6 w-full md:w-3/5 focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50" placeholder="请输入标识" />
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-baseline" x-data="quillEditor(`{{ old('content', $about->content) }}`)" x-init="init()">
          <label for="content" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">主要内容</label>
          <div class="md:w-3/5">
            <input type="hidden" id="content" name="content" x-model.debounce="content">
            <div x-ref="quillEditor" class="bg-white">
              {!! old('content', $about->content) !!}
            </div>
          </div>
        </div>
        <div class="space-y-1 md:space-y-0 md:flex md:items-center">
          <label for="cover" class="font-semibold md:w-1/5 flex-none md:mr-6 text-right">状态</label>
          <div class="w-full md:w-3/5 space-x-6">
            @foreach(\App\Models\About::$statusMap as $key => $value)
              <label class="inline-flex items-center space-x-2">
                <input id="status" type="radio" name="status" value="{{ $key }}" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300" {{ old('status', $about->status) == $key ? 'checked' : '' }}>
                <span>{{ $value }}</span>
              </label>
            @endforeach
          </div>
        </div>
        <div class="md:w-4/5 ml-auto space-x-2">
          <button type="submit" class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none md:ml-6 px-4 py-2 leading-5 text-sm rounded border-indigo-700 bg-indigo-700 text-white hover:text-white hover:bg-indigo-800 hover:border-indigo-800 focus:ring focus:ring-indigo-500 focus:ring-opacity-50 active:bg-indigo-700 active:border-indigo-700">
            确认
          </button>
          <button type="button" x-on:click="window.history.back()" class="inline-flex justify-center items-center space-x-2 rounded border font-semibold focus:outline-none px-4 py-2 leading-5 text-sm border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
            返回
          </button>
        </div>
      </form>
    </div>
  </div>
@endsection

@push('styles')
  <link rel="stylesheet" href="{{ mix('vendor/quill/quill.css') }}">
@endpush

@push('beforeScripts')
  <script src="{{ mix('vendor/quill/quill.js') }}"></script>
@endpush

@push('scripts')
  <script>
    function quillEditor(content) {
      return {
        content: content,

        init() {
          let that = this
          quill = new Quill(this.$refs.quillEditor, {
            modules: {
              toolbar: {
                container: [
                  [{ 'size': ['small', false, 'large', 'huge'] }],
                  [{'header': 2}, {'header': 3}],
                  ['bold', 'italic', 'underline', 'strike'],
                  ['link', 'blockquote', 'code-block', 'image'],
                  [{ list: 'ordered' }, { list: 'bullet' }, { 'align': [false, 'center', 'right', 'justify']}]
                ]
              }
            },
            theme: 'snow',
            scrollingContainer: 'html, body',
            placeholder: '请输入内容'
          })
          quill.on('text-change', function () {
            that.content = quill.getText() ? quill.root.innerHTML : ''
          })
        }
      }
    }
  </script>
@endpush

resources/views/admin/abouts/index.blade.php
@extends('layouts.admin')
@section('title', '卡片')

@section('breadcrumb')
  <x-breadcrumb.list>
    <x-breadcrumb.item href="{{ route('admin.dashboard') }}">仪表盘</x-breadcrumb.item>
    <x-breadcrumb.item href="{{ route('admin.cards.index') }}">关于我们</x-breadcrumb.item>
    <x-breadcrumb.item>列表</x-breadcrumb.item>
  </x-breadcrumb.list>
@endsection

@section('content')
  <div class="flex flex-col rounded shadow-sm bg-white overflow-hidden">
    <div class="py-4 px-5 lg:px-6 flex-grow w-full">
      <form action="{{ route('admin.abouts.index') }}" method="get" class="space-y-3 sm:space-y-0 sm:flex sm:items-center sm:space-x-4">
        <div class="flex items-center space-x-1">
          <label for="name" class="flex-shrink-0 text-sm">名称：</label>
          <input type="text" id="name" name="name" value="{{ old('name', request()->name) }}" class="block border border-gray-200 rounded px-3 py-2 leading-5 text-sm w-full focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50" placeholder="名称" />
        </div>
        <div class="flex items-center space-x-1">
          <label for="key" class="flex-shrink-0 text-sm">标识：</label>
          <input type="text" id="key" name="key" value="{{ old('key', request()->key) }}" class="block border border-gray-200 rounded px-3 py-2 leading-5 text-sm w-full focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50" placeholder="标识" />
        </div>
        <div class="space-x-2">
          <button type="submit" class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none px-4 py-2 leading-5 text-sm rounded border-indigo-700 bg-indigo-700 text-white hover:text-white hover:bg-indigo-800 hover:border-indigo-800 focus:ring focus:ring-indigo-500 focus:ring-opacity-50 active:bg-indigo-700 active:border-indigo-700">
            <span>搜索</span>
          </button>
          <a href="{{ route('admin.abouts.index') }}" class="inline-flex justify-center items-center space-x-2 rounded border font-semibold focus:outline-none px-4 py-2 leading-5 text-sm border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
            <span>清空</span>
          </a>
        </div>
      </form>
    </div>
  </div>
  <div class="flex flex-col rounded shadow-sm bg-white overflow-hidden">
    <div class="p-5 lg:p-6 flex-grow w-full space-y-4">
      <a href="{{ route('admin.abouts.create') }}" class="inline-flex justify-center items-center space-x-2 border font-semibold focus:outline-none px-4 py-2 leading-5 text-sm rounded border-indigo-700 bg-indigo-700 text-white hover:text-white hover:bg-indigo-800 hover:border-indigo-800 focus:ring focus:ring-indigo-500 focus:ring-opacity-50 active:bg-indigo-700 active:border-indigo-700">
        <x-heroicon-s-plus class="w-5 h-5 -mx-1" />
        <span>添加</span>
      </a>
      <div class="border border-gray-100 rounded overflow-x-auto min-w-full bg-white">
        <table class="min-w-full text-sm align-middle whitespace-nowrap">
          <thead>
          <tr class="text-gray-700 bg-gray-50 font-semibold">
            <th class="py-3 px-6 text-left">名称</th>
            <th class="py-3 px-6">标识</th>
            <th class="py-3 px-6">内容</th>
            <th class="py-3 px-6">状态</th>
            <th class="py-3 px-6">创建时间</th>
            <th class="py-3 px-6">操作</th>
          </tr>
          </thead>

          <tbody>
          @if($abouts->isNotEmpty())
            @foreach($abouts as $about)
              <tr class="border-t border-gray-100">
                <td class="py-3 px-6">
                  <span class="text-base text-gray-700">{{ $about->name }}</span>
                </td>
                <td class="py-3 px-6 text-center">
                  <span class="text-gray-500">{{ $about->key }}</span>
                </td>
                <td class="py-3 px-6 text-center">
                  <a href="javascript:;" x-on:click="$dispatch('init-dialog-list', { open: true, action: `{{ route('admin.abouts.showContent', $about) }}` })" class="text-base text-indigo-600 hover:text-indigo-700 hover:underline">查看内容</a>
                </td>
                <td class="py-3 px-6 text-center">
                  @if($about->status)
                    <span class="inline-flex items-center rounded-full py-1 px-2.5 text-sm leading-none text-green-800 bg-green-100">启用</span>
                  @else
                    <span class="inline-flex items-center rounded-full py-1 px-2.5 text-sm leading-none text-red-800 bg-red-100">禁用</span>
                  @endif
                </td>
                <td class="py-3 px-6 text-center">
                  <span class="text-gray-500">{{ $about->created_at }}</span>
                </td>
                <td class="py-3 px-6 text-center">
                  <a href="{{ route('admin.abouts.edit', $about) }}" class="inline-flex justify-center items-center space-x-1 border font-semibold focus:outline-none px-2 py-1 leading-5 text-sm rounded border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
                    <x-heroicon-s-pencil  class="w-4 h-4"/>
                    <span>编辑</span>
                  </a>
                  <button x-on:click="$dispatch('confirm-delete', { open: true, action: `{{ route('admin.abouts.destroy', $about) }}` })" type="button" class="inline-flex justify-center items-center space-x-1 border font-semibold focus:outline-none px-2 py-1 leading-5 text-sm rounded border-gray-300 bg-white text-gray-800 shadow-sm hover:text-gray-800 hover:bg-gray-100 hover:border-gray-300 hover:shadow focus:ring focus:ring-gray-500 focus:ring-opacity-25 active:bg-white active:border-white active:shadow-none">
                    <x-heroicon-s-trash  class="w-4 h-4"/>
                    <span>删除</span>
                  </button>
                </td>
              </tr>
            @endforeach
          @else
            <tr class="border-t border-gray-100">
              <td class="py-6 px-6 text-center text-gray-500" colspan="6">暂无数据。</td>
            </tr>
          @endif
          </tbody>
        </table>
      </div>
      <div>
        {{ $abouts->withQueryString()->links('partials.admin.pagination') }}
      </div>
    </div>
  </div>
  <x-dialog.list title="查看内容"></x-dialog.list>
  <x-dialog.confirm-delete>
    <p class="text-gray-600">是否删除该内容？</p>
  </x-dialog.confirm-delete>
@endsection

resources/views/admin/abouts/show-content.blade.php
<div class="ql-editor">
  {!! $about->content !!}
</div>